# Generated by Django 4.2.7 on 2023-11-07 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_alter_comentarios_bd_autor_and_more'),
        ('Website', '0006_alter_comentarios_bd_comentario'),
    ]

    operations = [
    ]
