# Generated by Django 4.2.3 on 2023-10-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos_bd',
            name='foto',
            field=models.ImageField(default='', upload_to='./images'),
        ),
    ]
