# Generated by Django 4.2.7 on 2023-11-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_fotos_bd_comentario_fotos_bd_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos_bd',
            name='comentario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.comentarios_bd'),
        ),
        migrations.AlterField(
            model_name='fotos_bd',
            name='like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.like_bd'),
        ),
    ]
