# Generated by Django 4.2.3 on 2023-10-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0002_fotos_bd_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos_bd',
            name='data_foto',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='comentarios_bd',
            name='data_comentario',
            field=models.DateField(default=''),
        ),
    ]
