# Generated by Django 4.2.7 on 2023-11-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_remove_fotos_bd_comentario_remove_fotos_bd_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barra_Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
