# Generated by Django 4.2.4 on 2023-11-07 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_barra_pesquisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios_bd',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.fotos_bd'),
        ),
        migrations.AlterField(
            model_name='comentarios_bd',
            name='comentario',
            field=models.TextField(),
        ),
    ]
