# Generated by Django 4.2.6 on 2023-11-23 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website', '0007_merge_20231106_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca_BD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos_BD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('foto', models.ImageField(upload_to='images/')),
                ('descricao', models.TextField(max_length=255)),
                ('preco', models.TextField(max_length=255)),
                ('data_foto', models.DateField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.marca_bd')),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho_BD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Tecido_BD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecido', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_BD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='fotos_bd',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='like_bd',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Comentarios_BD',
        ),
        migrations.DeleteModel(
            name='Fotos_BD',
        ),
        migrations.DeleteModel(
            name='Like_BD',
        ),
        migrations.AddField(
            model_name='produtos_bd',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.tamanho_bd'),
        ),
        migrations.AddField(
            model_name='produtos_bd',
            name='tecido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.tecido_bd'),
        ),
        migrations.AddField(
            model_name='produtos_bd',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.tipo_bd'),
        ),
    ]
