# Generated by Django 4.2.6 on 2023-11-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_marca_bd_produtos_bd_tamanho_bd_tecido_bd_tipo_bd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca_bd',
            name='marca',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tecido_bd',
            name='tecido',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tipo_bd',
            name='tipo',
            field=models.CharField(max_length=15),
        ),
    ]
