# Generated by Django 4.2.6 on 2023-11-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0010_alter_produtos_bd_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos_bd',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Unisex', 'Unisex')], default='Unisex', max_length=20),
        ),
    ]
