# Generated by Django 4.2.6 on 2023-12-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0015_alter_pedido_bd_data_pedido_alter_pedido_bd_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_bd',
            name='cartaonome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido_bd',
            name='cartaonumero',
            field=models.CharField(default='', max_length=26),
        ),
        migrations.AddField(
            model_name='pedido_bd',
            name='codseguranca',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='pedido_bd',
            name='dataexpira',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='pedido_bd',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Cancelado', 'Cancelado'), ('Entregue', 'Entregado')], default='Pendente', max_length=20),
        ),
    ]
