# Generated by Django 4.2.6 on 2023-12-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0016_pedido_bd_cartaonome_pedido_bd_cartaonumero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_bd',
            name='codseguranca',
            field=models.CharField(default='', max_length=4),
        ),
    ]
