# Generated by Django 4.2.6 on 2023-12-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0017_alter_pedido_bd_codseguranca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_bd',
            name='endereco_entrega',
            field=models.CharField(max_length=255),
        ),
    ]
