# Generated by Django 4.2.7 on 2023-11-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='imagem',
            field=models.ImageField(default='img-01-big', upload_to='imagens/'),
        ),
    ]
