# Generated by Django 4.2.7 on 2023-11-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginate', '0002_fotos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='imagem',
            field=models.ImageField(default='1', upload_to='./imagens'),
        ),
    ]
