# Generated by Django 4.2.7 on 2023-11-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginate', '0004_alter_fotos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='imagem',
            field=models.ImageField(default=None, upload_to='./imagens'),
        ),
    ]
