# Generated by Django 4.2.7 on 2023-11-04 16:12

import Paginate.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Paginate', '0005_alter_fotos_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotos',
            name='id',
        ),
        migrations.AddField(
            model_name='fotos',
            name='id_foto',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=Paginate.models.upload_image_foto),
        ),
    ]
