-- MySQL Script generated by MySQL Workbench
-- Mon Nov 27 22:13:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pi202302
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pi202302
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pi202302` DEFAULT CHARACTER SET utf8 ;
USE `pi202302` ;

-- -----------------------------------------------------
-- Table `pi202302`.`Tamanho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi202302`.`Tamanho` (
  `idTamanho` INT NOT NULL AUTO_INCREMENT,
  `tamanho` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`idTamanho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi202302`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi202302`.`Marca` (
  `idMarca` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi202302`.`Tecido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi202302`.`Tecido` (
  `idTecido` INT NOT NULL AUTO_INCREMENT,
  `tecido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTecido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi202302`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi202302`.`Tipo` (
  `idTipo` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi202302`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi202302`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `is_staff` INT NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi202302`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi202302`.`Produtos` (
  `idProdutos` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(5,2) NOT NULL,
  `genero` VARCHAR(20) NOT NULL,
  `foto` BLOB NOT NULL,
  `User_idUser` INT NOT NULL,
  `Tipo_idTipo` INT NOT NULL,
  `Tecido_idTecido` INT NOT NULL,
  `Tamanho_idTamanho` INT NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  PRIMARY KEY (`idProdutos`, `User_idUser`, `Tipo_idTipo`, `Tecido_idTecido`, `Tamanho_idTamanho`, `Marca_idMarca`),
  INDEX `fk_Produtos_User_idx` (`User_idUser` ASC) ,
  INDEX `fk_Produtos_Tipo1_idx` (`Tipo_idTipo` ASC) ,
  INDEX `fk_Produtos_Tecido1_idx` (`Tecido_idTecido` ASC) ,
  INDEX `fk_Produtos_Tamanho1_idx` (`Tamanho_idTamanho` ASC) ,
  INDEX `fk_Produtos_Marca1_idx` (`Marca_idMarca` ASC) ,
  CONSTRAINT `fk_Produtos_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `pi202302`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_Tipo1`
    FOREIGN KEY (`Tipo_idTipo`)
    REFERENCES `pi202302`.`Tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_Tecido1`
    FOREIGN KEY (`Tecido_idTecido`)
    REFERENCES `pi202302`.`Tecido` (`idTecido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_Tamanho1`
    FOREIGN KEY (`Tamanho_idTamanho`)
    REFERENCES `pi202302`.`Tamanho` (`idTamanho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `pi202302`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi202302`.`Checkout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi202302`.`Checkout` (
  `idCheckout` INT NOT NULL AUTO_INCREMENT,
  `Produtos_idProdutos` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idCheckout`, `Produtos_idProdutos`, `User_idUser`),
  INDEX `fk_Checkout_Produtos1_idx` (`Produtos_idProdutos` ASC) ,
  INDEX `fk_Checkout_User1_idx` (`User_idUser` ASC) ,
  CONSTRAINT `fk_Checkout_Produtos1`
    FOREIGN KEY (`Produtos_idProdutos`)
    REFERENCES `pi202302`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Checkout_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `pi202302`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
